### ISSUE TITLE
What tutorial did you use to know how to make this?

### ISSUE THREAD

**Issue by 12944qwerty** [Kenny2github/deathly_hallows#3]
^ Honestly, I thought I knew everything there was about python. I know now that I am wrong..

**Comment by Kenny2github** [comment]
I didn't use any tutorials; anything I learned while making this was through Google and StackOverflow. I also make use of [my MediaWiki library](https://github.com/Kenny2github/mw-api-client) which has even more stuff.

I love comparing programming languages to spoken languages, so think of it this way: once you know the grammar of a language, the only thing left is the vocabulary, which you have to look up. When learning a programming language, focus on the syntax; anything you do with it will get more sophisticated with time.
