### ISSUE TITLE
Umm...

### ISSUE THREAD

**Issue by Nambaseking01** [Kenny2github/deathly_hallows#4]
Why is the title for your bot "deathly_hallows"?

I know that is a Harry Potter port (I am a huge Potterhead), but say whaaaaat?

**Comment by Kenny2github** [comment]
My bot was originally meant to run under my Scratch alt account Deathly_Hallows, and I had this thing set up under that premise, but scmb1 didn't like the name (even after the Wiki account Deathly_Hallows was created) so we had to switch to TemplatesFTW.

A side effect of that is that I am the only person with credentials for three accounts :/
